project:
  type: website
  output-dir: docs
  
execute:
  echo: true
  warning: true
  message: true

website:
  title: "SBDL"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - readme.qmd
      - data.qmd
      - tutorials.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

